### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by GoChartingAdmin** [wch/downloader#11]
Hi,

I am trying to query a URL and getting the below error

Peer certificate cannot be authenticated with given CA certificates

Kindly suggest a solution

**Comment by wch** [comment]
Can you provide an example?

From what I can tell, this is likely caused by your computer having outdated certificates, or from the server having an outdated certificate.

**Comment by GoChartingAdmin** [comment]
https://vrise.in/market/equity/corporate-information/quaterly-results/502/Vedanta

**Comment by wch** [comment]
It works fine for me on multiple platforms. You probably need to update the certificates on your computer. The specific instructions for that varies across platforms but if you search for "Peer certificate cannot be authenticated with given CA certificates", you should find the information you need.
