### ISSUE TITLE
downloaded pdf file could not be read by Acrobat Reader!

### ISSUE THREAD

**Issue by brdhungana** [wch/downloader#7]
The download was successful but pdf could not be opened / read.
library(downloader)
download("https://ssl.www8.hp.com/ww/en/secure/pdf/4aa5-3281enw.pdf"
                ,"4aa5-3281enw.pdf" 
                ,mode = "wb"
                ,cacheOK = FALSE
                 );

trying URL 'https://ssl.www8.hp.com/ww/en/secure/pdf/4aa5-3281enw.pdf'
Content type 'text/html; charset=UTF-8' length 200 bytes
opened URL
downloaded 102 Kb

#Try to open pdf file
shell.exec("C:/Users/XXXX/4aa5-3281enw.pdf");

#Got an error: "Acrobat could not open '4aa5-3281enw.pdf' because it is not a supported file type or because the file has been damaged ....."

However, I could manually download the pdf file that could be read without any issue!  Is there anything (like encryption) to do with 'ssl'  inside url link which is a secured site? 

If you want to try out with the above url link, please paste the link and fill out the form at HP site. Then you could run R code.  Thank you.

#System Information::
$platform
[1] "x86_64-w64-mingw32" 
$version.string
[1] "R version 3.1.0 (2014-04-10)"
downloader_0.4

**Comment by brdhungana** [comment]
However, I could successfully download other pdf(s) and read them without any issue:

> download("https://cran.r-project.org/web/packages/downloader/downloader.pdf"
+          ,"downloader.pdf"
+          ,mode="wb"
+          ,cacheOK = FALSE
+         );
trying URL 'https://cran.r-project.org/web/packages/downloader/downloader.pdf'
Content type 'application/pdf' length 76865 bytes (75 Kb)
opened URL
downloaded 75 Kb

> shell.exec("C:/Users/dhunganb/RProject/TextMining/TextMining_2/downloader.pdf");

**Comment by brdhungana** [comment]
It turns out that download() converts the pdf to htm format while writing in a disk. It maybe because html is an internal format for the document and pdf is the format for display. I am still not sure what 'option' could save file as pdf. 

download("https://ssl.www8.hp.com/ww/en/secure/pdf/4aa5-3281enw.pdf"
,"4aa5-3281enw.htm"
,mode = "wb"
,cacheOK = FALSE
);
shell.exec("C:/Users/***/4aa5-3281enw.htm");

Thanks.

**Comment by wch** [comment]
I'm not able to download the PDF in a browser. It gets redirected to a web page. That's probably what's happening when you call `download()`. If you're able to get that PDF in your browser, it's probably because that URL requires a cookie that your browser has. If that's the case, downloader probably isn't the right tool for this.
